version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: portalyus-postgres
    environment:
      POSTGRES_DB: portalyus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - portalyus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portalyus-backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/portalyus
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      UPLOAD_DIR: uploads
      MAX_FILE_SIZE: 100000000
      RUST_LOG: info
    ports:
      - "8000:8000"
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - portalyus-network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portalyus-frontend
    environment:
      PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    networks:
      - portalyus-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis (for future caching/sessions)
  redis:
    image: redis:7-alpine
    container_name: portalyus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - portalyus-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  backend_uploads:
    driver: local
  redis_data:
    driver: local

networks:
  portalyus-network:
    driver: bridge